delete from room;
delete from building;
insert into building (id,building_name) values (1,'Гл.здание');
insert into room (id,room_name,building_id,shift_id,profile_id) values (1,'каб1',1,11,14);
insert into room (id,room_name,building_id,shift_id,profile_id) values (2,'каб2',1,11,14);
insert into room (id,room_name,building_id,shift_id,profile_id) values (3,'каб3',1,11,14);
insert into room (id,room_name,building_id,shift_id,profile_id) values (4,'каб4',1,11,14);
insert into room (id,room_name,building_id,shift_id,profile_id) values (5,'каб5',1,11,14);
insert into room (id,room_name,building_id,shift_id,profile_id) values (6,'каб6',1,11,14);
insert into room (id,room_name,building_id,shift_id,profile_id) values (7,'каб7',1,11,14);
insert into room (id,room_name,building_id,shift_id,profile_id) values (8,'каб8',1,11,14);
insert into room (id,room_name,building_id,shift_id,profile_id) values (9,'каб9',1,11,14);
insert into room (id,room_name,building_id,shift_id,profile_id) values (10,'каб10',1,11,14);
insert into room (id,room_name,building_id,shift_id,profile_id) values (11,'каб11',1,11,14);
insert into room (id,room_name,building_id,shift_id,profile_id) values (12,'каб12',1,11,14);
insert into room (id,room_name,building_id,shift_id,profile_id) values (13,'каб13',1,11,14);
insert into room (id,room_name,building_id,shift_id,profile_id) values (14,'каб14',1,11,14);
insert into room (id,room_name,building_id,shift_id,profile_id) values (15,'каб15',1,11,14);
insert into room (id,room_name,building_id,shift_id,profile_id) values (16,'каб16',1,11,14);
insert into room (id,room_name,building_id,shift_id,profile_id) values (17,'каб17',1,11,14);
insert into room (id,room_name,building_id,shift_id,profile_id) values (18,'каб18',1,11,14);
insert into room (id,room_name,building_id,shift_id,profile_id) values (19,'каб19',1,11,14);
insert into room (id,room_name,building_id,shift_id,profile_id) values (20,'каб20',1,11,14);
insert into room (id,room_name,building_id,shift_id,profile_id) values (21,'каб21',1,11,14);
insert into room (id,room_name,building_id,shift_id,profile_id) values (22,'каб22',1,11,14);
insert into room (id,room_name,building_id,shift_id,profile_id) values (23,'каб23',1,11,14);
insert into room (id,room_name,building_id,shift_id,profile_id) values (24,'каб24',1,11,14);
insert into room (id,room_name,building_id,shift_id,profile_id) values (25,'каб25',1,11,14);
insert into room (id,room_name,building_id,shift_id,profile_id) values (26,'каб26',1,11,14);
insert into room (id,room_name,building_id,shift_id,profile_id) values (27,'каб27',1,11,14);
insert into room (id,room_name,building_id,shift_id,profile_id) values (28,'каб28',1,11,14);
insert into room (id,room_name,building_id,shift_id,profile_id) values (29,'каб29',1,11,14);
insert into room (id,room_name,building_id,shift_id,profile_id) values (30,'каб30',1,11,14);
select * from room;
