delete from room;
delete from building;
insert into building (id,building_name) values (1,'Гл.здание');
insert into room (id,room_name,building_id,shift_id,profile_id) values (1,'каб 1',1,11,14);
insert into room (id,room_name,building_id,shift_id,profile_id) values (2,'каб 2',1,11,14);
insert into room (id,room_name,building_id,shift_id,profile_id) values (3,'каб 3',1,11,14);
insert into room (id,room_name,building_id,shift_id,profile_id) values (4,'каб 4',1,11,14);
insert into room (id,room_name,building_id,shift_id,profile_id) values (5,'каб 5',1,11,14);
insert into room (id,room_name,building_id,shift_id,profile_id) values (6,'каб 6',1,11,14);
insert into room (id,room_name,building_id,shift_id,profile_id) values (7,'каб 7',1,11,14);
insert into room (id,room_name,building_id,shift_id,profile_id) values (8,'каб 8',1,11,14);
insert into room (id,room_name,building_id,shift_id,profile_id) values (9,'каб 9',1,11,14);
insert into room (id,room_name,building_id,shift_id,profile_id) values (10,'каб 10',1,11,14);
insert into room (id,room_name,building_id,shift_id,profile_id) values (11,'каб 11',1,11,14);
insert into room (id,room_name,building_id,shift_id,profile_id) values (12,'каб 12',1,11,14);
insert into room (id,room_name,building_id,shift_id,profile_id) values (13,'каб 13',1,11,14);
insert into room (id,room_name,building_id,shift_id,profile_id) values (14,'каб 14',1,11,14);
insert into room (id,room_name,building_id,shift_id,profile_id) values (15,'каб 15',1,11,14);
insert into room (id,room_name,building_id,shift_id,profile_id) values (16,'каб 16',1,11,14);
insert into room (id,room_name,building_id,shift_id,profile_id) values (17,'каб 17',1,11,14);
insert into room (id,room_name,building_id,shift_id,profile_id) values (18,'каб 18',1,11,14);
insert into room (id,room_name,building_id,shift_id,profile_id) values (19,'каб 19',1,11,14);
insert into room (id,room_name,building_id,shift_id,profile_id) values (20,'каб 20',1,11,14);
insert into room (id,room_name,building_id,shift_id,profile_id) values (21,'каб 21',1,11,14);
insert into room (id,room_name,building_id,shift_id,profile_id) values (22,'каб 22',1,11,14);
insert into room (id,room_name,building_id,shift_id,profile_id) values (23,'каб 23',1,11,14);
insert into room (id,room_name,building_id,shift_id,profile_id) values (24,'каб 24',1,11,14);
insert into room (id,room_name,building_id,shift_id,profile_id) values (25,'каб 25',1,11,14);
insert into room (id,room_name,building_id,shift_id,profile_id) values (26,'каб 26',1,11,14);
insert into room (id,room_name,building_id,shift_id,profile_id) values (27,'каб 27',1,11,14);
insert into room (id,room_name,building_id,shift_id,profile_id) values (28,'каб 28',1,11,14);
insert into room (id,room_name,building_id,shift_id,profile_id) values (29,'каб 29',1,11,15);
insert into room (id,room_name,building_id,shift_id,profile_id) values (30,'каб 30',1,11,16);
select * from room;
